# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'SingaporePower' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.6'
    pod 'PKHUD', '~> 5.0'
    

end


target 'SingaporePowerTests' do
    use_frameworks!
    pod 'Nimble'
    pod 'Quick'
end
target 'SingaporePowerUITests' do
    use_frameworks!
    pod 'Nimble'
    pod 'Quick'
end
